name: 🔄 Lint | Renovate
on:
  pull_request

permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Renovate config validator
        run: npm install --global renovate
      - name: Test that the config is valid
        run: renovate-config-validator
